version: "3.9"

services:

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - postgres
